[package]
name = "snark-coordinator-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.92"
structopt = "0.3.26"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
